-- CreateTable
CREATE TABLE "TrustedProcess" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "comm" TEXT NOT NULL,
    "args" TEXT NOT NULL,
    "added_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
